# Ansible Playbook for Subutai Blockchain II blueprint
#
# Implemented by Lars Boegild Thomsen <lbthomsen@gmail.com>
#
---

- hosts: all
  remote_user: root
  tasks:

    - name: Disable dpkg fsync
      shell: echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io
      args: 
        creates: /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Create biab user
      user:
        name: biab
        group: users
        shell: /bin/bash

    - name: Install dirmngr
      apt:
        name: dirmngr
        state: present

    - name: Add ethereum repo key
      apt_key:
        id: "1C52189C923F6CA9"
        keyserver: keyserver.ubuntu.com

    - name: Add ethereum repo
      apt_repository:
        repo: deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main
        state: present

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - sudo
        - ethereum 

- hosts: bn
  remote_user: root
  tasks:

    - name: Generate bootnode key
      shell: bootnode -genkey /etc/bootnode.key
      args: 
        creates: /etc/bootnode.key

    - name: Fetch bootnode key
      shell: bootnode --nodekey /etc/bootnode.key --writeaddress
      register: bootnode_key_fetch

    - name: Store bootnode key
      set_fact: 
        bootnode_key: "{{ bootnode_key_fetch.stdout }}"

    - name: Fetch bootnode hostname
      shell: hostname
      register: bootnode_hostname_fetch

    - name: Store bootnode hostname
      set_fact: 
        bootnode_hostname: "{{ bootnode_hostname_fetch.stdout }}"

    - name: Install bootnode service
      template:
        src: files/bootnode.service
        dest: /lib/systemd/system

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Make sure bootnode.service is enabled
      shell: systemctl enable bootnode
      args:
        creates: /etc/systemd/system/multi-user.target.wants/bootnode.service

    - name: Restart boonode
      systemd:
        name: bootnode
        state: restarted

    - name: Copy Genesis
      template:
        src: files/genesis.json
        dest: /etc

    - name: Initialize blockchain
      shell: geth --datadir .ethereum/{{ ethereum_network }} init /etc/genesis.json
      args: 
        creates: /home/biab/.ethereum/{{ ethereum_network }}/geth/chaindata/000001.log
      become: yes
      become_user: biab

- hosts: all
  remote_user: root
  tasks:

    - name: Set geth default
      template:
        src: files/geth.default
        dest: /etc/default/geth

    - name: Install geth.service
      template: 
        src: files/geth.service
        dest: /lib/systemd/system

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Make sure geth.service is enabled
      shell: systemctl enable geth
      args:
        creates: /etc/systemd/system/multi-user.target.wants/geth.service

    - name: Restart geth
      systemd:
        name: geth
        state: restarted

# vim: ts=4 et nowrap autoindent